# Follow Instagram : hxrun.777
# Subscribe YouTube : Haroen Legend

from random import choice
import time

print('--- Selamat datang ke Cek Khodam ---')
answer = 'y'
while answer == 'y':
    khodam = choice(["Martabak Cokelat",
        "Naga Sakti",
        "Ratu Pantai Selatan",
        "Harimau Putih",
        "Raja Iblis bjir",
        "Dewi Bulan",
        "Penjaga Hutan",
        "Singa Emas",
        "Traktaktak",
        "Banteng Sakti",
        "Elang Perkasa",
        "Laba-laba Sunda",
        "Buaya Hitam",
        "Katak Sigma",
        "Ambatukam",
        "God Eater",
        "Skibidi Sigma",
        "Ikan Lohan Tidak Gyat",
        "Burung Puyuh Warna Bjir",
        "Monyet Hutan",
        "Gajah Ngawi",
        "Bloodbath",
        "Kursi Mewing",
        "Balon Ku Sigma",
        "Di Hina Tetap Sigma",
        "Kue Keju Viral",
        "Rehan Wangsaff",
        "Rehan Faceboff",
        "Rehan Instagraff",
        "Orang Hitam",
        "Si paling khodam",
        "Fajar mendadak hitam",
        "Ikbal Hotwil",
        "Kuda Pake Sendal",
        "Sendal Tobrut",
        "Jaket Bapak",
        "Kambing Hitam",
        "Pintu Gerbang",
        "Kayu Jati ",
        "Jati Diri",
        "Supra Bapak",
        "Ayam Tidak Punya KTP",
        "Dino Sok Inggris",
        "Bibir Jontor Badag",
        "Teh Sari Wangi",
        "Indomi Kecap Asin",
        "Burung Elang Dari Jawa",
        "Tidak Ada/Kosong !",
        "Nokia Bapak",
        "Telur Gulung",
        "Sayur Asem Kecap Manis",
        "Baju Terbang",
        "Sendal Jepit",
        "Nasi Padang",
        "Pizza Mewah",
        "Jus Alpukat",
        "Sate Ayam",
        "Gado-Gado Adit",
        "Kambing Guling",
        "Tahu Bulat",
        "Lontong Balap",
        "Soto Ayam",
        "Bakso Gepeng",
        "Cilok Kenyal",
        "Mie Ayam Lezat",
        "Es Cendol Manis",
        "Kopi Hitam Mantap",
        "Brownies Lumer",
        "Kerak Telor",
        "Tempe Mendoan",
        "Jajanan Pasar",
        "Pecel Lele",
        "Ayam Geprek",
        "Roti Bakar",
        "Pisang Goreng",
        "Bubur Ayam",
        "Abdul.exe",
        "Nasi Goreng Spesial",
        "Sop Buntut",
        "Gule Kambing",
        "Onde mande",
        "Rawon Hitam",
        "Ikan Bakar",
        "Sate Kambing",
        "Kue Cubit",
        "Agus menolak Khodam",
        "Tahu Gejrot",
        "Cyber Security"
        "Kacang Polong",
        "Sayur Bayam",
        "Sambal Terasi",
        "Es Dawet",
        "Teh Tarik",
        "Es Teler Premium",
        "Kerupuk Kulit",
        "Rengginang",
        "Emping Melinjo",
        "Mie Goreng",
        "Risoles Kun",
        "Lumpia Semarang",
        "Pempek Palembang",
        "Asinan Betawi",
        "Black Hat",
        "White Hat",
        "Lemper Ayam",
        "Bika Ambon",
        "Knalpot Supra",
        "Kue Lumpur",
        "HuTao wangy",
        "Putu Ayu",
        "Onde-Onde",
        "Serabi Uchiha",
        "Martabak Telur",
        "Bubur Ketan Hitam",
        "Es Dawet Ketan Hitam Pekat",
        "Oli Bekas",
        "Kai Cenat Mode Sigma",
        "Bocil Mewing",
        "Kapten Bajak Laut Ngawi",
        "Kak Gem Mode Mewing",
        "Uni Bakwan",
        "Fajar Sadboy",
        "Adit-Chan",
        "Sambal Goreng Kecap Hitam",
        "Tidak Ada",
        "Ambatron Type 555 - y 9 UZ",
        "Ambatukam Mewing",
        "Mas Rusdi Tidak G4Y",
        "Suki Liar",
        "Suki Type G4"])
    print()
    nama = input('Masukkan nama : ')
    time.sleep(3)
    print('Khodam anda   :' ,khodam)
    answer = input('Ulangi? [y/n] : ')
